#include <pebble.h>

// Message keys (generated by the build into message_keys.auto.c)
extern uint32_t MESSAGE_KEY_SYNC_REQUEST;
extern uint32_t MESSAGE_KEY_DONE_COUNT;
extern uint32_t MESSAGE_KEY_DONE_IDS;
extern uint32_t MESSAGE_KEY_SYNC_STATUS;
extern uint32_t MESSAGE_KEY_ITEM_COUNT;
extern uint32_t MESSAGE_KEY_ITEM_INDEX;
extern uint32_t MESSAGE_KEY_ITEM_ID;
extern uint32_t MESSAGE_KEY_ITEM_NAME;
extern uint32_t MESSAGE_KEY_ITEM_AMOUNT;
extern uint32_t MESSAGE_KEY_SYNC_MSG;

#define MAX_ITEMS 64
#define NAME_LEN 32
#define AMOUNT_LEN 16
#define STATUS_BUF_LEN 40

#define PERSIST_VERSION 1
#define PERSIST_KEY 1

typedef struct {
  uint32_t id;
  char name[NAME_LEN];
  char amount[AMOUNT_LEN];
  bool checked;
  bool pending_done;
} ShoppingItem;

typedef enum { SYNC_START = 0, SYNC_ITEM = 1, SYNC_DONE = 2, SYNC_FAIL = 3 } SyncStatus;

static Window *s_window;
static TextLayer *s_title_layer;
static TextLayer *s_count_layer;
static TextLayer *s_updated_layer;
static TextLayer *s_empty_layer;
static MenuLayer *s_menu_layer;

static ShoppingItem s_items[MAX_ITEMS];
static int s_item_count = 0;
static bool s_syncing = false;
static char s_count_buf[32];
static char s_status_buf[STATUS_BUF_LEN];

// --------------------------------------------------------- persistence

typedef struct {
  uint32_t version;
  int32_t item_count;
  char status[STATUS_BUF_LEN];
  ShoppingItem items[MAX_ITEMS];
} PersistData;

static void save_items(void) {
  PersistData pd;
  memset(&pd, 0, sizeof(pd));
  pd.version = PERSIST_VERSION;
  pd.item_count = s_item_count;
  strncpy(pd.status, s_status_buf, STATUS_BUF_LEN - 1);
  for (int i = 0; i < s_item_count; i++) {
    pd.items[i] = s_items[i];
  }
  persist_write_data(PERSIST_KEY, &pd, sizeof(pd));
}

static void load_items(void) {
  PersistData pd;
  int bytes = persist_read_data(PERSIST_KEY, &pd, sizeof(pd));
  if (bytes > 0 && pd.version == PERSIST_VERSION) {
    s_item_count = pd.item_count > MAX_ITEMS ? MAX_ITEMS : pd.item_count;
    for (int i = 0; i < s_item_count; i++) {
      s_items[i] = pd.items[i];
    }
    strncpy(s_status_buf, pd.status, STATUS_BUF_LEN - 1);
  } else {
    s_item_count = 0;
    s_status_buf[0] = '\0';
  }
}

// --------------------------------------------------------- status / count

static void set_status(const char *s) {
  snprintf(s_status_buf, sizeof(s_status_buf), "%s", s);
  text_layer_set_text(s_updated_layer, s_status_buf);
}

static void set_status_synced(void) {
  time_t now = time(NULL);
  struct tm *t = localtime(&now);
  strftime(s_status_buf, sizeof(s_status_buf), "Synced %H:%M", t);
  text_layer_set_text(s_updated_layer, s_status_buf);
}

static void update_count(void) {
  int checked = 0;
  for (int i = 0; i < s_item_count; i++) {
    if (s_items[i].checked) checked++;
  }
  snprintf(s_count_buf, sizeof(s_count_buf), "%d/%d done", checked, s_item_count);
  text_layer_set_text(s_count_layer, s_count_buf);
}

static void update_empty(void) {
  if (s_item_count == 0) {
    layer_set_hidden(text_layer_get_layer(s_empty_layer), false);
  } else {
    layer_set_hidden(text_layer_get_layer(s_empty_layer), true);
  }
}

// --------------------------------------------------------- sync

static void start_sync(void) {
  if (s_syncing) return;

  int n = 0;
  for (int i = 0; i < s_item_count; i++) {
    if (s_items[i].pending_done) n++;
  }

  DictionaryIterator *iter;
  if (app_message_outbox_begin(&iter) != APP_MSG_OK) {
    set_status("bt error");
    return;
  }
  dict_write_uint8(iter, MESSAGE_KEY_SYNC_REQUEST, 1);
  dict_write_uint8(iter, MESSAGE_KEY_DONE_COUNT, n);

  if (n > 0) {
    static uint32_t ids[MAX_ITEMS];
    int j = 0;
    for (int i = 0; i < s_item_count && j < n; i++) {
      if (s_items[i].pending_done) {
        ids[j++] = s_items[i].id;
      }
    }
    dict_write_data(iter, MESSAGE_KEY_DONE_IDS, (uint8_t *)ids, n * sizeof(uint32_t));
  }

  if (app_message_outbox_send() != APP_MSG_OK) {
    set_status("bt error");
    return;
  }

  s_syncing = true;
  set_status("Syncing...");
  menu_layer_reload_data(s_menu_layer);
}

// --------------------------------------------------------- menu layer

static uint16_t menu_get_num_sections(MenuLayer *ml, void *ctx) { return 1; }

static uint16_t menu_get_num_rows(MenuLayer *ml, uint16_t sec, void *ctx) {
  return s_item_count + 1;  // +1 for the "Sync now" row
}

static int16_t menu_get_cell_height(MenuLayer *ml, MenuIndex *idx, void *ctx) {
  return (idx->row == s_item_count) ? 32 : 40;
}

static void menu_draw_row(GContext *ctx, const Layer *cell, MenuIndex *idx, void *d) {
  GRect bounds = layer_get_bounds(cell);
  bool hl = menu_cell_layer_is_highlighted(cell);

  // "Sync now" row at the bottom
  if (idx->row == s_item_count) {
    GColor row_color = hl ? GColorWhite : GColorDarkCandyAppleRed;
    GColor text_color = hl ? GColorWhite : GColorBlack;

    // draw separator line at top
    graphics_context_set_stroke_color(ctx, hl ? GColorWhite : GColorLightGray);
    graphics_draw_line(ctx, GPoint(0, 0), GPoint(bounds.size.w, 0));

    graphics_context_set_text_color(ctx, text_color);
    graphics_draw_text(ctx, s_status_buf,
                       fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD),
                       GRect(4, 0, bounds.size.w - 8, bounds.size.h),
                       GTextOverflowModeTrailingEllipsis,
                       GTextAlignmentCenter, NULL);
    return;
  }

  if (idx->row >= s_item_count) return;
  ShoppingItem *item = &s_items[idx->row];

  GColor text_color = hl ? GColorWhite : (item->checked ? GColorDarkGray : GColorBlack);
  GColor sub_color = hl ? GColorWhite : GColorDarkGray;

  // checkbox
  GRect box = GRect(5, (bounds.size.h - 14) / 2, 14, 14);
  graphics_context_set_stroke_color(ctx, hl ? GColorWhite : GColorBlack);
  graphics_context_set_stroke_width(ctx, 1);
  graphics_draw_rect(ctx, box);
  if (item->checked) {
    graphics_context_set_stroke_color(ctx, hl ? GColorWhite : GColorGreen);
    graphics_context_set_stroke_width(ctx, 2);
    graphics_draw_line(ctx, GPoint(box.origin.x + 2, box.origin.y + 7),
                       GPoint(box.origin.x + 5, box.origin.y + 11));
    graphics_draw_line(ctx, GPoint(box.origin.x + 5, box.origin.y + 11),
                       GPoint(box.origin.x + 12, box.origin.y + 2));
  }

  const int tx = 26;
  const int tw = bounds.size.w - tx - 4;

  // name
  GRect name_rect = GRect(tx, 0, tw, 22);
  graphics_context_set_text_color(ctx, text_color);
  graphics_draw_text(ctx, item->name,
                     fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD),
                     name_rect, GTextOverflowModeTrailingEllipsis,
                     GTextAlignmentLeft, NULL);

  // strikethrough
  if (item->checked) {
    int sw = (int)strlen(item->name) * 9;
    if (sw > tw) sw = tw;
    if (sw < 10) sw = 10;
    graphics_context_set_stroke_color(ctx, text_color);
    graphics_context_set_stroke_width(ctx, 1);
    graphics_draw_line(ctx, GPoint(tx, 11), GPoint(tx + sw, 11));
  }

  // amount
  graphics_context_set_text_color(ctx, sub_color);
  graphics_draw_text(ctx, item->amount,
                     fonts_get_system_font(FONT_KEY_GOTHIC_14),
                     GRect(tx, 21, tw, 16),
                     GTextOverflowModeTrailingEllipsis,
                     GTextAlignmentLeft, NULL);
}

static void menu_select_click(MenuLayer *ml, MenuIndex *idx, void *d) {
  // "Sync now" row
  if (idx->row == s_item_count) {
    start_sync();
    return;
  }
  if (idx->row >= s_item_count) return;
  ShoppingItem *it = &s_items[idx->row];
  it->checked = !it->checked;
  it->pending_done = it->checked;
  layer_mark_dirty(menu_layer_get_layer(ml));
  update_count();
  save_items();
  vibes_short_pulse();
}

static void menu_select_long_click(MenuLayer *ml, MenuIndex *idx, void *d) {
  start_sync();
}

// --------------------------------------------------------- messages

static void inbox_received(DictionaryIterator *iter, void *ctx) {
  Tuple *st = dict_find(iter, MESSAGE_KEY_SYNC_STATUS);
  if (!st) return;

  switch (st->value->uint8) {
    case SYNC_START:
      s_item_count = 0;
      menu_layer_reload_data(s_menu_layer);
      update_empty();
      break;

    case SYNC_ITEM: {
      Tuple *t_id = dict_find(iter, MESSAGE_KEY_ITEM_ID);
      Tuple *t_name = dict_find(iter, MESSAGE_KEY_ITEM_NAME);
      Tuple *t_amount = dict_find(iter, MESSAGE_KEY_ITEM_AMOUNT);
      if (s_item_count < MAX_ITEMS && t_id && t_name) {
        ShoppingItem *it = &s_items[s_item_count++];
        // Read id regardless of sender's uint8/uint16/uint32 encoding
        if (t_id->length == 1)      it->id = t_id->value->uint8;
        else if (t_id->length == 2) it->id = t_id->value->uint16;
        else                        it->id = t_id->value->uint32;
        strncpy(it->name, t_name->value->cstring, NAME_LEN - 1);
        it->name[NAME_LEN - 1] = '\0';
        strncpy(it->amount, t_amount ? t_amount->value->cstring : "", AMOUNT_LEN - 1);
        it->amount[AMOUNT_LEN - 1] = '\0';
        it->checked = false;
        it->pending_done = false;
        menu_layer_reload_data(s_menu_layer);
        update_empty();
      }
      break;
    }

    case SYNC_DONE:
      s_syncing = false;
      set_status_synced();
      update_count();
      update_empty();
      menu_layer_reload_data(s_menu_layer);
      save_items();
      vibes_short_pulse();
      break;

    case SYNC_FAIL: {
      s_syncing = false;
      Tuple *msg = dict_find(iter, MESSAGE_KEY_SYNC_MSG);
      set_status(msg ? msg->value->cstring : "Sync failed");
      update_empty();
      menu_layer_reload_data(s_menu_layer);
      vibes_double_pulse();
      break;
    }
  }
}

static void outbox_failed(DictionaryIterator *iter, AppMessageResult reason, void *ctx) {
  s_syncing = false;
  set_status("bt error");
  menu_layer_reload_data(s_menu_layer);
}

// --------------------------------------------------------- window

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  GRect bounds = layer_get_bounds(root);

  // title bar
  s_title_layer = text_layer_create(GRect(0, 0, bounds.size.w, 26));
  text_layer_set_background_color(s_title_layer, GColorDarkCandyAppleRed);
  text_layer_set_text_color(s_title_layer, GColorWhite);
  text_layer_set_font(s_title_layer, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(s_title_layer, " tandooPEB");
  layer_add_child(root, text_layer_get_layer(s_title_layer));

  s_count_layer = text_layer_create(GRect(bounds.size.w - 84, 5, 80, 18));
  text_layer_set_background_color(s_count_layer, GColorClear);
  text_layer_set_text_color(s_count_layer, GColorWhite);
  text_layer_set_font(s_count_layer, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(s_count_layer, GTextAlignmentRight);
  layer_add_child(root, text_layer_get_layer(s_count_layer));

  // status line
  s_updated_layer = text_layer_create(GRect(0, 28, bounds.size.w, 18));
  text_layer_set_background_color(s_updated_layer, GColorClear);
  text_layer_set_text_color(s_updated_layer, GColorDarkGray);
  text_layer_set_font(s_updated_layer, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  layer_add_child(root, text_layer_get_layer(s_updated_layer));

  // menu
  s_menu_layer = menu_layer_create(GRect(0, 48, bounds.size.w, bounds.size.h - 48));
  menu_layer_set_callbacks(s_menu_layer, NULL, (MenuLayerCallbacks) {
    .get_num_sections  = menu_get_num_sections,
    .get_num_rows      = menu_get_num_rows,
    .get_cell_height   = menu_get_cell_height,
    .draw_row          = menu_draw_row,
    .select_click      = menu_select_click,
    .select_long_click = menu_select_long_click,
  });
  menu_layer_set_highlight_colors(s_menu_layer, GColorDarkCandyAppleRed, GColorWhite);
  menu_layer_set_click_config_onto_window(s_menu_layer, window);
  layer_add_child(root, menu_layer_get_layer(s_menu_layer));

  // empty state
  s_empty_layer = text_layer_create(GRect(0, 100, bounds.size.w, 60));
  text_layer_set_background_color(s_empty_layer, GColorClear);
  text_layer_set_text_color(s_empty_layer, GColorDarkGray);
  text_layer_set_font(s_empty_layer, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text_alignment(s_empty_layer, GTextAlignmentCenter);
  text_layer_set_overflow_mode(s_empty_layer, GTextOverflowModeWordWrap);
  text_layer_set_text(s_empty_layer, "No items.\nLong-press SELECT\nto sync.");
  layer_add_child(root, text_layer_get_layer(s_empty_layer));

  update_count();
  update_empty();
}

static void window_unload(Window *window) {
  text_layer_destroy(s_empty_layer);
  menu_layer_destroy(s_menu_layer);
  text_layer_destroy(s_updated_layer);
  text_layer_destroy(s_count_layer);
  text_layer_destroy(s_title_layer);
}

// --------------------------------------------------------- init / deinit

static void init(void) {
  load_items();
  strncpy(s_status_buf, "Sync now", STATUS_BUF_LEN - 1);

  app_message_register_inbox_received(inbox_received);
  app_message_register_outbox_failed(outbox_failed);
  app_message_open(1024, 512);

  s_window = window_create();
  window_set_background_color(s_window, GColorWhite);
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load   = window_load,
    .unload = window_unload,
  });
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
