#include <pebble.h>

// Message keys (generated by the build into message_keys.auto.c)
extern uint32_t MESSAGE_KEY_SYNC_REQUEST;
extern uint32_t MESSAGE_KEY_NEW_COUNT;
extern uint32_t MESSAGE_KEY_NEW_ITEMS;
extern uint32_t MESSAGE_KEY_DONE_COUNT;
extern uint32_t MESSAGE_KEY_DONE_IDS;
extern uint32_t MESSAGE_KEY_SYNC_STATUS;
extern uint32_t MESSAGE_KEY_ITEM_COUNT;
extern uint32_t MESSAGE_KEY_ITEM_INDEX;
extern uint32_t MESSAGE_KEY_ITEM_ID;
extern uint32_t MESSAGE_KEY_ITEM_NAME;
extern uint32_t MESSAGE_KEY_ITEM_AMOUNT;
extern uint32_t MESSAGE_KEY_SYNC_MSG;

#define MAX_ITEMS 64
#define NAME_LEN 32
#define AMOUNT_LEN 16
#define STATUS_BUF_LEN 40
#define DICTATION_BUF_LEN 64
#define NEW_ITEMS_MAX 16   // new local items sent per sync (bounded app message)

#define PERSIST_SCHEMA_VERSION 1   // schema version of the persisted format
#define PERSIST_KEY_VERSION    1   // persist key storing the schema version

typedef struct {
  uint32_t id;
  char name[NAME_LEN];
  char amount[AMOUNT_LEN];
  bool checked;
  bool pending_done;
  bool local;          // added on the watch, not yet created on the server
} ShoppingItem;

typedef enum { SYNC_START = 0, SYNC_ITEM = 1, SYNC_DONE = 2, SYNC_FAIL = 3 } SyncStatus;

static Window *s_window;
static Window *s_prompt_window;
static TextLayer *s_prompt_text_layer;
static ActionBarLayer *s_prompt_action_bar;
static GBitmap *s_prompt_sync_bitmap;
static GBitmap *s_prompt_exit_bitmap;
static AppTimer *s_exit_safety_timer;
static Layer *s_title_bg_layer;
static TextLayer *s_title_layer;
static TextLayer *s_count_layer;
static TextLayer *s_empty_layer;
static MenuLayer *s_menu_layer;
static BitmapLayer *s_logo_layer;
static GBitmap *s_logo_bitmap;
static DictationSession *s_dictation_session;

static ShoppingItem s_items[MAX_ITEMS];
static int s_item_count = 0;
static bool s_syncing = false;
static bool s_has_synced = false;
static bool s_exit_after_sync = false;
static char s_count_buf[32];
static char s_status_buf[STATUS_BUF_LEN];

// --------------------------------------------------------- persistence

#define PERSIST_KEY_VERSION    1
#define PERSIST_KEY_COUNT      2
#define PERSIST_KEY_HAS_SYNCED 3
#define PERSIST_KEY_STATUS     4
#define PERSIST_KEY_IDS_BASE   100
#define PERSIST_KEY_NAMES_BASE 200
#define PERSIST_KEY_AMTS_BASE  300
#define PERSIST_KEY_FLAGS_BASE 400

static void save_items(void) {
  persist_write_int(PERSIST_KEY_VERSION, PERSIST_SCHEMA_VERSION);
  persist_write_int(PERSIST_KEY_COUNT, s_item_count);
  persist_write_int(PERSIST_KEY_HAS_SYNCED, s_has_synced ? 1 : 0);
  persist_write_string(PERSIST_KEY_STATUS, s_status_buf);

  for (int i = 0; i < s_item_count; i++) {
    persist_write_data(PERSIST_KEY_IDS_BASE + i, &s_items[i].id, sizeof(uint32_t));
    persist_write_string(PERSIST_KEY_NAMES_BASE + i, s_items[i].name);
    persist_write_string(PERSIST_KEY_AMTS_BASE + i, s_items[i].amount);
    uint8_t flags = (s_items[i].checked ? 1 : 0) | (s_items[i].pending_done ? 2 : 0) |
                    (s_items[i].local ? 4 : 0);
    persist_write_data(PERSIST_KEY_FLAGS_BASE + i, &flags, 1);
  }
}

static void load_items(void) {
  if (persist_read_int(PERSIST_KEY_VERSION) != PERSIST_SCHEMA_VERSION) {
    s_item_count = 0;
    s_status_buf[0] = '\0';
    s_has_synced = false;
    return;
  }

  s_item_count = persist_read_int(PERSIST_KEY_COUNT);
  if (s_item_count < 0 || s_item_count > MAX_ITEMS) s_item_count = 0;

  s_has_synced = persist_read_int(PERSIST_KEY_HAS_SYNCED) == 1;

  if (persist_read_string(PERSIST_KEY_STATUS, s_status_buf, STATUS_BUF_LEN) < 0) {
    s_status_buf[0] = '\0';
  }

  for (int i = 0; i < s_item_count; i++) {
    uint32_t id;
    persist_read_data(PERSIST_KEY_IDS_BASE + i, &id, sizeof(uint32_t));
    s_items[i].id = id;

    if (persist_read_string(PERSIST_KEY_NAMES_BASE + i, s_items[i].name, NAME_LEN) < 0) {
      s_items[i].name[0] = '\0';
    }
    if (persist_read_string(PERSIST_KEY_AMTS_BASE + i, s_items[i].amount, AMOUNT_LEN) < 0) {
      s_items[i].amount[0] = '\0';
    }

    uint8_t flags = 0;
    persist_read_data(PERSIST_KEY_FLAGS_BASE + i, &flags, 1);
    s_items[i].checked = (flags & 1) != 0;
    s_items[i].pending_done = (flags & 2) != 0;
    s_items[i].local = (flags & 4) != 0;
  }
}

// --------------------------------------------------------- status / count

#define ACCENT_COLOR GColorFromHEX(0x0156B2)

static void title_bg_update(Layer *layer, GContext *ctx) {
  GRect bounds = layer_get_bounds(layer);
  graphics_context_set_fill_color(ctx, ACCENT_COLOR);
  graphics_fill_rect(ctx, bounds, 0, GCornerNone);
}

static void set_status(const char *s) {
  snprintf(s_status_buf, sizeof(s_status_buf), "%s", s);
}

static void set_status_synced(void) {
  time_t now = time(NULL);
  struct tm *t = localtime(&now);
  strftime(s_status_buf, sizeof(s_status_buf), "Synced %H:%M", t);
  s_has_synced = true;
}

static void update_count(void) {
  int checked = 0;
  for (int i = 0; i < s_item_count; i++) {
    if (s_items[i].checked) checked++;
  }
  snprintf(s_count_buf, sizeof(s_count_buf), "%d/%d done", checked, s_item_count);
  text_layer_set_text(s_count_layer, s_count_buf);
}

static void update_empty(void) {
  if (s_item_count == 0) {
    layer_set_hidden(text_layer_get_layer(s_empty_layer), false);
  } else {
    layer_set_hidden(text_layer_get_layer(s_empty_layer), true);
  }
}

// --------------------------------------------------------- sync

static void start_sync(void) {
  if (s_syncing) return;

  int n_done = 0;
  int n_new = 0;
  for (int i = 0; i < s_item_count; i++) {
    if (s_items[i].local) {
      if (n_new < NEW_ITEMS_MAX) n_new++;
    } else if (s_items[i].pending_done) {
      n_done++;
    }
  }

  DictionaryIterator *iter;
  if (app_message_outbox_begin(&iter) != APP_MSG_OK) {
    set_status("bt error");
    return;
  }
  dict_write_uint8(iter, MESSAGE_KEY_SYNC_REQUEST, 1);
  dict_write_uint8(iter, MESSAGE_KEY_DONE_COUNT, n_done);

  if (n_done > 0) {
    static uint32_t ids[MAX_ITEMS];
    int j = 0;
    for (int i = 0; i < s_item_count && j < n_done; i++) {
      if (!s_items[i].local && s_items[i].pending_done) {
        ids[j++] = s_items[i].id;
      }
    }
    dict_write_data(iter, MESSAGE_KEY_DONE_IDS, (uint8_t *)ids, n_done * sizeof(uint32_t));
  }

  // New local items: "c\tname" per line (c = '1' when checked done)
  dict_write_uint8(iter, MESSAGE_KEY_NEW_COUNT, n_new);
  if (n_new > 0) {
    static char buf[NEW_ITEMS_MAX * (NAME_LEN + 2) + 1];
    int p = 0;
    int written = 0;
    for (int i = 0; i < s_item_count && written < n_new; i++) {
      if (!s_items[i].local) continue;
      if (written > 0) buf[p++] = '\n';
      buf[p++] = s_items[i].checked ? '1' : '0';
      buf[p++] = '\t';
      int len = strlen(s_items[i].name);
      if (len > NAME_LEN - 1) len = NAME_LEN - 1;
      memcpy(&buf[p], s_items[i].name, len);
      p += len;
      written++;
    }
    buf[p] = '\0';
    dict_write_cstring(iter, MESSAGE_KEY_NEW_ITEMS, buf);
  }

  if (app_message_outbox_send() != APP_MSG_OK) {
    set_status("bt error");
    return;
  }

  s_syncing = true;
  set_status("Syncing...");
  menu_layer_reload_data(s_menu_layer);
}

// --------------------------------------------------------- menu layer

static int open_count(void) {
  int c = 0;
  for (int i = 0; i < s_item_count; i++) {
    if (!s_items[i].checked) c++;
  }
  return c;
}

static void add_local_item(const char *text) {
  if (s_item_count >= MAX_ITEMS) {
    set_status("List full");
    menu_layer_reload_data(s_menu_layer);
    return;
  }

  // All local items must fit in one sync request, otherwise a sync would
  // drop the ones that didn't fit when it replaces the list.
  int n_local = 0;
  for (int i = 0; i < s_item_count; i++) {
    if (s_items[i].local) n_local++;
  }
  if (n_local >= NEW_ITEMS_MAX) {
    set_status("Sync to add more");
    menu_layer_reload_data(s_menu_layer);
    return;
  }

  const char *start = text;
  while (*start == ' ' || *start == '\t' || *start == '\n') start++;

  char name[NAME_LEN];
  strncpy(name, start, NAME_LEN - 1);
  name[NAME_LEN - 1] = '\0';
  int len = strlen(name);
  while (len > 0 && (name[len - 1] == ' ' || name[len - 1] == '\t' || name[len - 1] == '\n')) {
    name[--len] = '\0';
  }
  if (len == 0) {
    set_status("Nothing heard");
    menu_layer_reload_data(s_menu_layer);
    return;
  }

  // insert at the end of the open section
  int at = open_count();
  memmove(&s_items[at + 1], &s_items[at], (s_item_count - at) * sizeof(ShoppingItem));
  ShoppingItem *it = &s_items[at];
  it->id = 0;
  strncpy(it->name, name, NAME_LEN - 1);
  it->name[NAME_LEN - 1] = '\0';
  it->amount[0] = '\0';
  it->checked = false;
  it->pending_done = false;
  it->local = true;
  s_item_count++;

  save_items();
  update_count();
  update_empty();
  set_status("Added - sync to save");
  menu_layer_reload_data(s_menu_layer);
  vibes_short_pulse();
}

static void dictation_session_callback(DictationSession *session,
                                       DictationSessionStatus status,
                                       char *transcription, void *context) {
  // Non-success statuses (cancel, no speech, connectivity) are surfaced by
  // the system dictation UI itself; only act on an accepted transcription.
  if (status != DictationSessionStatusSuccess) return;
  add_local_item(transcription);
}

static bool has_unsynced(void) {
  for (int i = 0; i < s_item_count; i++) {
    if (s_items[i].pending_done || s_items[i].local) return true;
  }
  return false;
}

static void move_item(int from, int to) {
  if (from == to) return;
  ShoppingItem tmp = s_items[from];
  if (from < to) {
    memmove(&s_items[from], &s_items[from + 1], (to - from) * sizeof(ShoppingItem));
  } else {
    memmove(&s_items[to + 1], &s_items[to], (from - to) * sizeof(ShoppingItem));
  }
  s_items[to] = tmp;
}

static struct {
  bool valid;
  ShoppingItem item;
  int prev_index;
} s_undo;

#define SCROLL_GAP 20
#define SCROLL_STEP 2
#define SCROLL_PERIOD 40
static int s_scroll_offset = 0;
static int s_scroll_row = -1;
static AppTimer *s_scroll_timer = NULL;

static int text_width(const char *text, GFont font) {
  if (!text || !text[0]) return 0;
  GSize s = graphics_text_layout_get_content_size(
      text, font, GRect(0, 0, 1000, 30),
      GTextOverflowModeWordWrap, GTextAlignmentLeft);
  return s.w;
}

static bool item_overflows(int row) {
  if (row <= 0 || row - 1 >= s_item_count) return false;
  ShoppingItem *item = &s_items[row - 1];
  GRect b = layer_get_bounds(menu_layer_get_layer(s_menu_layer));
  int amt_w = text_width(item->amount, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  int amt_x = b.size.w - 4 - amt_w;
  if (amt_x < 28 + 10) amt_x = 28 + 10;
  int name_w = text_width(item->name, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  return name_w > (amt_x - 6) - 28;
}

static void reset_scroll(void) {
  if (s_scroll_timer) {
    app_timer_cancel(s_scroll_timer);
    s_scroll_timer = NULL;
  }
  s_scroll_offset = 0;
  s_scroll_row = -1;
}

static void scroll_tick(void *ctx) {
  s_scroll_timer = NULL;
  if (!s_menu_layer) return;

  MenuIndex sel = menu_layer_get_selected_index(s_menu_layer);
  if (!item_overflows(sel.row)) {
    reset_scroll();
    return;
  }
  ShoppingItem *item = &s_items[sel.row - 1];
  GFont font = fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD);
  int name_w = text_width(item->name, font);
  int total = name_w + SCROLL_GAP;

  s_scroll_offset += SCROLL_STEP;
  if (s_scroll_offset >= total) s_scroll_offset %= total;
  s_scroll_row = sel.row;
  layer_mark_dirty(menu_layer_get_layer(s_menu_layer));
  s_scroll_timer = app_timer_register(SCROLL_PERIOD, scroll_tick, NULL);
}

static void start_scroll(int row) {
  if (s_scroll_row != row) {
    s_scroll_row = row;
    s_scroll_offset = 0;
  }
  if (!s_scroll_timer) {
    s_scroll_timer = app_timer_register(SCROLL_PERIOD, scroll_tick, NULL);
  }
}

static uint16_t menu_get_num_sections(MenuLayer *ml, void *ctx) { return 1; }

static uint16_t menu_get_num_rows(MenuLayer *ml, uint16_t sec, void *ctx) {
  return s_item_count + 1;  // +1 for the "Sync now" row
}

static int16_t menu_get_cell_height(MenuLayer *ml, MenuIndex *idx, void *ctx) {
  return (idx->row == 0) ? 50 : 46;
}

static void menu_draw_row(GContext *ctx, const Layer *cell, MenuIndex *idx, void *d) {
  GRect bounds = layer_get_bounds(cell);
  bool hl = menu_cell_layer_is_highlighted(cell);

  // "Sync now" row at the top
  if (idx->row == 0) {
    GColor text_color = hl ? GColorWhite : GColorBlack;
    GColor sub_color = hl ? GColorWhite : GColorDarkGray;

    // line 1: status text (bold)
    int main_h = (s_has_synced && !s_syncing) ? 26 : bounds.size.h;
    graphics_context_set_text_color(ctx, text_color);
    graphics_draw_text(ctx, s_status_buf,
                       fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD),
                       GRect(4, 0, bounds.size.w - 8, main_h),
                       GTextOverflowModeTrailingEllipsis,
                       GTextAlignmentCenter, NULL);

    // line 2: "Press to refresh" (only when synced and not syncing)
    if (s_has_synced && !s_syncing) {
      graphics_context_set_text_color(ctx, sub_color);
      graphics_draw_text(ctx, "Press to refresh",
                         fonts_get_system_font(FONT_KEY_GOTHIC_18),
                         GRect(4, 26, bounds.size.w - 8, 22),
                         GTextOverflowModeTrailingEllipsis,
                         GTextAlignmentCenter, NULL);
    }
    return;
  }

  if (idx->row - 1 >= s_item_count) return;
  ShoppingItem *item = &s_items[idx->row - 1];

  GColor text_color = hl ? GColorWhite : (item->checked ? GColorDarkGray : GColorBlack);
  GColor sub_color = hl ? GColorWhite : GColorDarkGray;

  const int tx = 28;
  GFont name_font = fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD);
  GFont amt_font = fonts_get_system_font(FONT_KEY_GOTHIC_18);

  // amount width + right-aligned x
  int amt_w = text_width(item->amount, amt_font);
  int amt_x = bounds.size.w - 4 - amt_w;
  if (amt_x < tx + 10) amt_x = tx + 10;

  // name window: [tx, right]
  int right = amt_x - 6;
  int name_w = text_width(item->name, name_font);
  int name_box_w = right - tx;
  if (name_box_w < 10) name_box_w = 10;
  bool overflow = name_w > name_box_w;

  int y_name = (bounds.size.h - 24) / 2;
  bool is_marquee = overflow && hl;
  if (is_marquee) {
    start_scroll(idx->row);
    int off = s_scroll_offset;
    int total = name_w + SCROLL_GAP;

    // copy A: full text width, origin slides left
    graphics_context_set_text_color(ctx, text_color);
    graphics_draw_text(ctx, item->name, name_font,
                       GRect(tx - off, y_name, name_w, 24),
                       GTextOverflowModeTrailingEllipsis,
                       GTextAlignmentLeft, NULL);

    // copy B: re-enters from the right for a seamless loop
    int leftB = tx - off + total;
    if (leftB < right) {
      graphics_context_set_text_color(ctx, text_color);
      graphics_draw_text(ctx, item->name, name_font,
                         GRect(leftB, y_name, name_w, 24),
                         GTextOverflowModeTrailingEllipsis,
                         GTextAlignmentLeft, NULL);
    }

    // erase the strips outside the name window with the row background
    GColor bg = hl ? ACCENT_COLOR : GColorWhite;
    graphics_context_set_fill_color(ctx, bg);
    graphics_fill_rect(ctx, GRect(0, 0, tx, bounds.size.h), 0, GCornerNone);
    graphics_fill_rect(ctx, GRect(right, 0, bounds.size.w - right, bounds.size.h), 0, GCornerNone);
  } else {
    if (hl) reset_scroll();
    // static single-line name (clipped to the name box)
    graphics_context_set_text_color(ctx, text_color);
    graphics_draw_text(ctx, item->name, name_font,
                       GRect(tx, y_name, name_box_w, 24),
                       GTextOverflowModeTrailingEllipsis,
                       GTextAlignmentLeft, NULL);
  }

  // separator above the first done item (drawn after erasure)
  int oc = open_count();
  if (oc < s_item_count && (idx->row - 1) == oc) {
    graphics_context_set_stroke_color(ctx, hl ? GColorWhite : GColorLightGray);
    graphics_context_set_stroke_width(ctx, 1);
    graphics_draw_line(ctx, GPoint(0, 0), GPoint(bounds.size.w, 0));
  }

  // checkbox (drawn after erasure)
  GRect box = GRect(5, (bounds.size.h - 16) / 2, 16, 16);
  graphics_context_set_stroke_color(ctx, hl ? GColorWhite : GColorBlack);
  graphics_context_set_stroke_width(ctx, 1);
  graphics_draw_rect(ctx, box);
  if (item->checked) {
    graphics_context_set_stroke_color(ctx, hl ? GColorWhite : GColorGreen);
    graphics_context_set_stroke_width(ctx, 2);
    graphics_draw_line(ctx, GPoint(box.origin.x + 2, box.origin.y + 8),
                       GPoint(box.origin.x + 6, box.origin.y + 12));
    graphics_draw_line(ctx, GPoint(box.origin.x + 6, box.origin.y + 12),
                       GPoint(box.origin.x + 14, box.origin.y + 2));
  }

  // strikethrough across the visible name
  if (item->checked) {
    int x1, x2;
    if (is_marquee) {
      x1 = tx - s_scroll_offset;
      if (x1 < tx) x1 = tx;
      x2 = x1 + name_w;
      if (x2 > right) x2 = right;
    } else {
      x1 = tx;
      x2 = tx + name_w;
      if (x2 > right) x2 = right;
      if (x2 < x1 + 12) x2 = x1 + 12;
    }
    if (x2 > x1) {
      graphics_context_set_stroke_color(ctx, text_color);
      graphics_context_set_stroke_width(ctx, 1);
      graphics_draw_line(ctx, GPoint(x1, y_name + 13), GPoint(x2, y_name + 13));
    }
  }

  // amount, right-aligned on the same line
  graphics_context_set_text_color(ctx, sub_color);
  graphics_draw_text(ctx, item->amount, amt_font,
                     GRect(amt_x, (bounds.size.h - 18) / 2, bounds.size.w - 4 - amt_x, 18),
                     GTextOverflowModeTrailingEllipsis,
                     GTextAlignmentRight, NULL);
}

static void menu_select_click(MenuLayer *ml, MenuIndex *idx, void *d) {
  // "Sync now" row at the top
  if (idx->row == 0) {
    start_sync();
    return;
  }
  if (idx->row - 1 >= s_item_count) return;
  int item_index = idx->row - 1;
  ShoppingItem *it = &s_items[item_index];
  s_undo.item = *it;
  s_undo.prev_index = item_index;
  s_undo.valid = true;
  it->checked = !it->checked;
  it->pending_done = it->checked;
  move_item(item_index, it->checked ? open_count() : open_count() - 1);
  reset_scroll();
  menu_layer_reload_data(s_menu_layer);
  update_count();
  save_items();
  vibes_short_pulse();
}

static void menu_select_long_click(MenuLayer *ml, MenuIndex *idx, void *d) {
  if (!s_undo.valid) {
    set_status("Nothing to undo");
    menu_layer_reload_data(s_menu_layer);
    return;
  }

  int cur = -1;
  for (int i = 0; i < s_item_count; i++) {
    if (s_items[i].id == s_undo.item.id) { cur = i; break; }
  }
  if (cur < 0) {
    s_undo.valid = false;
    return;
  }

  // remove item from its current slot
  memmove(&s_items[cur], &s_items[cur + 1], (s_item_count - cur - 1) * sizeof(ShoppingItem));

  // insert the pre-toggle snapshot back at its original index
  int insert_at = s_undo.prev_index;
  if (cur < insert_at) insert_at--;
  if (insert_at > s_item_count - 1) insert_at = s_item_count - 1;
  if (insert_at < 0) insert_at = 0;
  memmove(&s_items[insert_at + 1], &s_items[insert_at], (s_item_count - insert_at - 1) * sizeof(ShoppingItem));
  s_items[insert_at] = s_undo.item;

  s_undo.valid = false;
  reset_scroll();
  menu_layer_reload_data(s_menu_layer);
  update_count();
  save_items();
  vibes_short_pulse();
}

// --------------------------------------------------------- exit prompt

static void exit_now(void) {
  window_stack_pop_all(true);
}

static void exit_timer_cb(void *ctx) {
  s_exit_safety_timer = NULL;
  exit_now();
}

// Main window handlers:
static void sync_then_exit(void) {
  // Start the sync; if the outbox can't even be used, exit immediately.
  start_sync();
  if (!s_syncing) {
    exit_now();
    return;
  }
  s_exit_after_sync = true;
  // Safety net in case the phone never answers.
  s_exit_safety_timer = app_timer_register(10000, exit_timer_cb, NULL);
}

// Prompt window handlers:
static void prompt_sync_click(ClickRecognizerRef rec, void *ctx) {
  window_stack_pop(true);            // close the dialog first
  sync_then_exit();
}

static void prompt_exit_click(ClickRecognizerRef rec, void *ctx) {
  exit_now();
}

static void prompt_click_config_provider(void *ctx) {
  window_single_click_subscribe(BUTTON_ID_SELECT, prompt_sync_click);
  window_single_click_subscribe(BUTTON_ID_DOWN, prompt_exit_click);
  window_single_click_subscribe(BUTTON_ID_BACK, prompt_exit_click);
}

static void prompt_window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  GRect bounds = layer_get_bounds(root);

  s_prompt_sync_bitmap = gbitmap_create_with_resource(RESOURCE_ID_SYNC_ICON);
  s_prompt_exit_bitmap = gbitmap_create_with_resource(RESOURCE_ID_EXIT_ICON);

  // message text, left of the action bar
  const GEdgeInsets label_insets = {.top = 40, .right = ACTION_BAR_WIDTH + 12, .bottom = 40, .left = 12};
  s_prompt_text_layer = text_layer_create(grect_inset(bounds, label_insets));
  text_layer_set_text(s_prompt_text_layer, "Unsynced changes.\nSync now?");
  text_layer_set_background_color(s_prompt_text_layer, GColorClear);
  text_layer_set_text_color(s_prompt_text_layer, GColorWhite);
  text_layer_set_text_alignment(s_prompt_text_layer, GTextAlignmentCenter);
  text_layer_set_overflow_mode(s_prompt_text_layer, GTextOverflowModeWordWrap);
  text_layer_set_font(s_prompt_text_layer, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  layer_add_child(root, text_layer_get_layer(s_prompt_text_layer));

  s_prompt_action_bar = action_bar_layer_create();
  action_bar_layer_set_icon(s_prompt_action_bar, BUTTON_ID_SELECT, s_prompt_sync_bitmap);
  action_bar_layer_set_icon(s_prompt_action_bar, BUTTON_ID_DOWN, s_prompt_exit_bitmap);
  action_bar_layer_set_click_config_provider(s_prompt_action_bar, prompt_click_config_provider);
  action_bar_layer_add_to_window(s_prompt_action_bar, window);
}

static void prompt_window_unload(Window *window) {
  if (s_exit_safety_timer) {
    app_timer_cancel(s_exit_safety_timer);
    s_exit_safety_timer = NULL;
  }
  text_layer_destroy(s_prompt_text_layer);
  action_bar_layer_destroy(s_prompt_action_bar);
  gbitmap_destroy(s_prompt_sync_bitmap);
  gbitmap_destroy(s_prompt_exit_bitmap);
  window_destroy(s_prompt_window);
  s_prompt_window = NULL;
}

static void show_sync_prompt(void) {
  s_prompt_window = window_create();
  window_set_background_color(s_prompt_window, ACCENT_COLOR);
  window_set_window_handlers(s_prompt_window, (WindowHandlers) {
    .load = prompt_window_load,
    .unload = prompt_window_unload,
  });
  window_stack_push(s_prompt_window, true);
}

// --------------------------------------------------------- window clicks

static void up_single_click(ClickRecognizerRef rec, void *ctx) {
  menu_layer_set_selected_next(s_menu_layer, true, MenuRowAlignCenter, true);
}

static void down_single_click(ClickRecognizerRef rec, void *ctx) {
  menu_layer_set_selected_next(s_menu_layer, false, MenuRowAlignCenter, true);
}

static void down_long_click(ClickRecognizerRef rec, void *ctx) {
  if (s_syncing) return;
  if (!s_dictation_session) {
    // Could not be created at launch (phone not connected yet); retry now.
    s_dictation_session = dictation_session_create(DICTATION_BUF_LEN,
                                                   dictation_session_callback, NULL);
  }
  if (!s_dictation_session) {
    set_status("Voice unavailable");
    menu_layer_reload_data(s_menu_layer);
    return;
  }
  dictation_session_start(s_dictation_session);
}

static void select_single_click(ClickRecognizerRef rec, void *ctx) {
  MenuIndex idx = menu_layer_get_selected_index(s_menu_layer);
  menu_select_click(s_menu_layer, &idx, NULL);
}

static void select_long_click(ClickRecognizerRef rec, void *ctx) {
  MenuIndex idx = menu_layer_get_selected_index(s_menu_layer);
  menu_select_long_click(s_menu_layer, &idx, NULL);
}

static void back_single_click(ClickRecognizerRef rec, void *ctx) {
  if (!s_syncing && has_unsynced()) {
    show_sync_prompt();
  } else {
    exit_now();
  }
}

static void main_click_config_provider(void *ctx) {
  window_single_repeating_click_subscribe(BUTTON_ID_UP, 100, (ClickHandler)up_single_click);
  window_single_repeating_click_subscribe(BUTTON_ID_DOWN, 100, (ClickHandler)down_single_click);
  window_long_click_subscribe(BUTTON_ID_DOWN, 0, (ClickHandler)down_long_click, NULL);
  window_single_click_subscribe(BUTTON_ID_SELECT, (ClickHandler)select_single_click);
  window_long_click_subscribe(BUTTON_ID_SELECT, 0, (ClickHandler)select_long_click, NULL);
  window_single_click_subscribe(BUTTON_ID_BACK, (ClickHandler)back_single_click);
}

// --------------------------------------------------------- messages

static void inbox_received(DictionaryIterator *iter, void *ctx) {
  Tuple *st = dict_find(iter, MESSAGE_KEY_SYNC_STATUS);
  if (!st) return;

  switch (st->value->uint8) {
    case SYNC_START:
      s_item_count = 0;
      s_undo.valid = false;
      reset_scroll();
      menu_layer_reload_data(s_menu_layer);
      update_empty();
      break;

    case SYNC_ITEM: {
      Tuple *t_id = dict_find(iter, MESSAGE_KEY_ITEM_ID);
      Tuple *t_name = dict_find(iter, MESSAGE_KEY_ITEM_NAME);
      Tuple *t_amount = dict_find(iter, MESSAGE_KEY_ITEM_AMOUNT);
      if (s_item_count < MAX_ITEMS && t_id && t_name) {
        ShoppingItem *it = &s_items[s_item_count++];
        // Read id regardless of sender's uint8/uint16/uint32 encoding
        if (t_id->length == 1)      it->id = t_id->value->uint8;
        else if (t_id->length == 2) it->id = t_id->value->uint16;
        else                        it->id = t_id->value->uint32;
        strncpy(it->name, t_name->value->cstring, NAME_LEN - 1);
        it->name[NAME_LEN - 1] = '\0';
        strncpy(it->amount, t_amount ? t_amount->value->cstring : "", AMOUNT_LEN - 1);
        it->amount[AMOUNT_LEN - 1] = '\0';
        it->checked = false;
        it->pending_done = false;
        menu_layer_reload_data(s_menu_layer);
        update_empty();
      }
      break;
    }

    case SYNC_DONE:
      s_syncing = false;
      s_undo.valid = false;
      set_status_synced();
      update_count();
      update_empty();
      menu_layer_reload_data(s_menu_layer);
      save_items();
      vibes_short_pulse();
      if (s_exit_after_sync) {
        s_exit_after_sync = false;
        exit_now();
      }
      break;

    case SYNC_FAIL: {
      s_syncing = false;
      Tuple *msg = dict_find(iter, MESSAGE_KEY_SYNC_MSG);
      set_status(msg ? msg->value->cstring : "Sync failed");
      update_empty();
      menu_layer_reload_data(s_menu_layer);
      vibes_double_pulse();
      if (s_exit_after_sync) {
        s_exit_after_sync = false;
        exit_now();
      }
      break;
    }
  }
}

static void outbox_failed(DictionaryIterator *iter, AppMessageResult reason, void *ctx) {
  s_syncing = false;
  set_status("bt error");
  menu_layer_reload_data(s_menu_layer);
  if (s_exit_after_sync) {
    s_exit_after_sync = false;
    exit_now();
  }
}

// --------------------------------------------------------- window

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  GRect bounds = layer_get_bounds(root);

  // title bar
  s_title_bg_layer = layer_create(GRect(0, 0, bounds.size.w, 30));
  layer_set_update_proc(s_title_bg_layer, title_bg_update);
  layer_add_child(root, s_title_bg_layer);

  s_title_layer = text_layer_create(GRect(24, 0, bounds.size.w - 24, 30));
  text_layer_set_background_color(s_title_layer, GColorClear);
  text_layer_set_text_color(s_title_layer, GColorWhite);
  text_layer_set_font(s_title_layer, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  text_layer_set_text(s_title_layer, "tandooPEB");
  layer_add_child(root, text_layer_get_layer(s_title_layer));

  s_logo_bitmap = gbitmap_create_with_resource(RESOURCE_ID_LOGO_ICON);
  s_logo_layer = bitmap_layer_create(GRect(2, 4, 22, 22));
  bitmap_layer_set_compositing_mode(s_logo_layer, GCompOpSet);
  bitmap_layer_set_bitmap(s_logo_layer, s_logo_bitmap);
  layer_add_child(root, bitmap_layer_get_layer(s_logo_layer));

  s_count_layer = text_layer_create(GRect(bounds.size.w - 100, 6, 96, 18));
  text_layer_set_background_color(s_count_layer, GColorClear);
  text_layer_set_text_color(s_count_layer, GColorWhite);
  text_layer_set_font(s_count_layer, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text_alignment(s_count_layer, GTextAlignmentRight);
  layer_add_child(root, text_layer_get_layer(s_count_layer));

  // shopping list
  s_menu_layer = menu_layer_create(GRect(0, 32, bounds.size.w, bounds.size.h - 32));
  menu_layer_set_callbacks(s_menu_layer, NULL, (MenuLayerCallbacks) {
    .get_num_sections  = menu_get_num_sections,
    .get_num_rows      = menu_get_num_rows,
    .get_cell_height   = menu_get_cell_height,
    .draw_row          = menu_draw_row,
  });
  menu_layer_set_highlight_colors(s_menu_layer, ACCENT_COLOR, GColorWhite);
  window_set_click_config_provider(s_window, main_click_config_provider);
  layer_add_child(root, menu_layer_get_layer(s_menu_layer));

  // empty state
  s_empty_layer = text_layer_create(GRect(0, 108, bounds.size.w, 60));
  text_layer_set_background_color(s_empty_layer, GColorClear);
  text_layer_set_text_color(s_empty_layer, GColorDarkGray);
  text_layer_set_font(s_empty_layer, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text_alignment(s_empty_layer, GTextAlignmentCenter);
  text_layer_set_overflow_mode(s_empty_layer, GTextOverflowModeWordWrap);
  text_layer_set_text(s_empty_layer, "No items.\nTop row syncs.\nHold DOWN to add.");
  layer_add_child(root, text_layer_get_layer(s_empty_layer));

  update_count();
  update_empty();
}

static void window_unload(Window *window) {
  reset_scroll();
  gbitmap_destroy(s_logo_bitmap);
  bitmap_layer_destroy(s_logo_layer);
  text_layer_destroy(s_empty_layer);
  menu_layer_destroy(s_menu_layer);
  text_layer_destroy(s_count_layer);
  text_layer_destroy(s_title_layer);
  layer_destroy(s_title_bg_layer);
}

// --------------------------------------------------------- init / deinit

static void init(void) {
  load_items();
  if (!s_has_synced) {
    strncpy(s_status_buf, "Sync now", STATUS_BUF_LEN - 1);
  }

  app_message_register_inbox_received(inbox_received);
  app_message_register_outbox_failed(outbox_failed);
  app_message_open(2048, 2048);

  s_dictation_session = dictation_session_create(DICTATION_BUF_LEN,
                                                 dictation_session_callback, NULL);

  s_window = window_create();
  window_set_background_color(s_window, GColorWhite);
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load   = window_load,
    .unload = window_unload,
  });
  window_stack_push(s_window, true);
}

static void deinit(void) {
  if (s_dictation_session) {
    dictation_session_destroy(s_dictation_session);
    s_dictation_session = NULL;
  }
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
